# Boston Dataset analysis

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

## Importing the Dataset

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [3]:
dataset = pd.DataFrame(boston['data'], columns=boston['feature_names'])
dataset['target'] = boston['target']
dataset

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset['target'].values

## Splitting the dataset into train and test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=0
)

## Feature scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Fitting the Simple Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[22.6   24.89 ]
 [50.    23.721]
 [23.    29.365]
 [ 8.3   12.122]
 [21.2   21.444]
 [19.9   19.283]
 [20.6   20.496]
 [18.7   21.361]
 [16.1   18.897]
 [18.6   19.928]
 [ 8.8    5.127]
 [17.2   16.387]
 [14.9   17.078]
 [10.5    5.594]
 [50.    39.996]
 [29.    32.497]
 [23.    22.458]
 [33.3   36.852]
 [29.4   30.864]
 [21.    23.151]
 [23.8   24.775]
 [19.1   24.672]
 [20.4   20.595]
 [29.1   30.354]
 [19.3   22.419]
 [23.1   10.233]
 [19.6   17.648]
 [19.4   18.274]
 [38.7   35.534]
 [18.7   20.961]
 [14.6   18.304]
 [20.    17.793]
 [20.5   19.966]
 [20.1   24.061]
 [23.6   29.102]
 [16.8   19.278]
 [ 5.6   11.155]
 [50.    24.576]
 [14.5   17.586]
 [13.3   15.495]
 [23.9   26.206]
 [20.    20.863]
 [19.8   22.315]
 [13.8   15.607]
 [16.5   23.004]
 [21.6   25.172]
 [20.3   20.115]
 [17.    22.903]
 [11.8   10.038]
 [27.5   24.285]
 [15.6   20.941]
 [23.1   17.353]
 [24.3   24.522]
 [42.8   29.951]
 [15.6   13.427]
 [21.7   21.727]
 [17.1   20.79 ]
 [17.2   15.497]
 [15.    13.99

In [9]:
# Accuracy
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5892223849182512

## Fitting linear SVR

In [10]:
from sklearn.svm import SVR
svr1 = SVR(kernel='linear')
svr1.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
y_pred = svr1.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[2.260e+01 2.503e+01]
 [5.000e+01 2.051e+01]
 [2.300e+01 2.661e+01]
 [8.300e+00 1.013e+01]
 [2.120e+01 2.143e+01]
 [1.990e+01 1.871e+01]
 [2.060e+01 1.912e+01]
 [1.870e+01 2.052e+01]
 [1.610e+01 1.670e+01]
 [1.860e+01 1.802e+01]
 [8.800e+00 1.486e+00]
 [1.720e+01 1.482e+01]
 [1.490e+01 1.692e+01]
 [1.050e+01 4.103e+00]
 [5.000e+01 3.731e+01]
 [2.900e+01 3.234e+01]
 [2.300e+01 2.089e+01]
 [3.330e+01 3.581e+01]
 [2.940e+01 2.938e+01]
 [2.100e+01 2.191e+01]
 [2.380e+01 2.415e+01]
 [1.910e+01 2.195e+01]
 [2.040e+01 1.975e+01]
 [2.910e+01 2.884e+01]
 [1.930e+01 2.132e+01]
 [2.310e+01 3.522e+00]
 [1.960e+01 1.726e+01]
 [1.940e+01 1.738e+01]
 [3.870e+01 3.527e+01]
 [1.870e+01 2.016e+01]
 [1.460e+01 1.715e+01]
 [2.000e+01 1.727e+01]
 [2.050e+01 1.950e+01]
 [2.010e+01 2.282e+01]
 [2.360e+01 2.664e+01]
 [1.680e+01 1.741e+01]
 [5.600e+00 1.134e+01]
 [5.000e+01 2.042e+01]
 [1.450e+01 1.566e+01]
 [1.330e+01 1.513e+01]
 [2.390e+01 2.558e+01]
 [2.000e+01 2.071e+01]
 [1.980e+01 2.240e+01]
 [1.380e+01

In [12]:
r2_score(y_test, y_pred)

0.5226828023558314

## Fitting the SVR Regression

In [13]:
from sklearn.svm import SVR
svr2 = SVR()
svr2.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
y_pred = svr2.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[22.6   25.208]
 [50.    18.933]
 [23.    24.58 ]
 [ 8.3   13.236]
 [21.2   21.1  ]
 [19.9   19.439]
 [20.6   20.815]
 [18.7   20.163]
 [16.1   19.08 ]
 [18.6   19.114]
 [ 8.8   20.831]
 [17.2   13.111]
 [14.9   14.844]
 [10.5   12.877]
 [50.    27.335]
 [29.    30.41 ]
 [23.    21.365]
 [33.3   31.802]
 [29.4   28.897]
 [21.    21.479]
 [23.8   23.857]
 [19.1   21.644]
 [20.4   18.917]
 [29.1   27.976]
 [19.3   20.603]
 [23.1   18.039]
 [19.6   17.151]
 [19.4   18.649]
 [38.7   34.062]
 [18.7   18.62 ]
 [14.6   15.251]
 [20.    17.293]
 [20.5   19.704]
 [20.1   21.431]
 [23.6   25.908]
 [16.8   20.902]
 [ 5.6   11.966]
 [50.    22.281]
 [14.5   13.992]
 [13.3   13.379]
 [23.9   23.648]
 [20.    20.376]
 [19.8   23.073]
 [13.8   15.06 ]
 [16.5   25.291]
 [21.6   23.384]
 [20.3   19.227]
 [17.    20.937]
 [11.8   16.79 ]
 [27.5   23.015]
 [15.6   20.747]
 [23.1   19.829]
 [24.3   21.496]
 [42.8   29.772]
 [15.6   15.362]
 [21.7   21.294]
 [17.1   20.077]
 [17.2   18.635]
 [15.    19.43

In [15]:
# Accuracy
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4957469419124396

### Grid Search for best parameters

In [18]:
from sklearn.model_selection import GridSearchCV
params = {
    'C' : [0.5, 1, 10],
    'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    'kernel': ('linear', 'rbf', 'poly')
}
grid_search = GridSearchCV(
    estimator=svr2,
    param_grid=params,
    cv=5,
    n_jobs=-1)
grid_search = grid_search.fit(X_train, y_train)

/home/its-k/anaconda3/envs/Learning/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [19]:
grid_search.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [20]:
grid_search.best_score_

0.8269557288365009

In [21]:
best_svr = grid_search.best_estimator_

In [22]:
y_pred = best_svr.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[22.6   22.893]
 [50.    20.989]
 [23.    25.137]
 [ 8.3   11.312]
 [21.2   20.497]
 [19.9   19.025]
 [20.6   22.235]
 [18.7   20.071]
 [16.1   22.532]
 [18.6   19.722]
 [ 8.8   18.696]
 [17.2   10.626]
 [14.9   14.83 ]
 [10.5    7.986]
 [50.    37.48 ]
 [29.    32.01 ]
 [23.    22.887]
 [33.3   35.972]
 [29.4   29.794]
 [21.    21.427]
 [23.8   23.487]
 [19.1   21.857]
 [20.4   20.193]
 [29.1   27.207]
 [19.3   20.928]
 [23.1   23.197]
 [19.6   16.918]
 [19.4   17.401]
 [38.7   39.903]
 [18.7   18.538]
 [14.6   15.377]
 [20.    18.031]
 [20.5   19.797]
 [20.1   19.202]
 [23.6   25.322]
 [16.8   19.988]
 [ 5.6    9.122]
 [50.    27.05 ]
 [14.5   13.778]
 [13.3   14.394]
 [23.9   23.978]
 [20.    21.473]
 [19.8   20.029]
 [13.8   17.345]
 [16.5   21.382]
 [21.6   23.463]
 [20.3   20.538]
 [17.    17.111]
 [11.8   15.748]
 [27.5   22.585]
 [15.6   19.896]
 [23.1   23.397]
 [24.3   21.664]
 [42.8   35.093]
 [15.6   14.11 ]
 [21.7   21.22 ]
 [17.1   17.94 ]
 [17.2   18.607]
 [15.    16.73

In [23]:
r2_score(y_test, y_pred)

0.6774386081797916

## Fitting DecisionTree Regression

In [24]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [25]:
y_pred = dt.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[22.6 23.7]
 [50.  20.2]
 [23.  18.5]
 [ 8.3 19.1]
 [21.2 20.8]
 [19.9 21.1]
 [20.6 20.3]
 [18.7 19. ]
 [16.1 24.5]
 [18.6 16.1]
 [ 8.8  7.2]
 [17.2 17.9]
 [14.9 12.6]
 [10.5  8.8]
 [50.  48.5]
 [29.  37. ]
 [23.  21.2]
 [33.3 34.6]
 [29.4 24. ]
 [21.  21.1]
 [23.8 24.7]
 [19.1 15.3]
 [20.4 20.3]
 [29.1 24.7]
 [19.3 19.7]
 [23.1 10.9]
 [19.6 14.5]
 [19.4 15.6]
 [38.7 41.7]
 [18.7 20.4]
 [14.6 11.7]
 [20.  19.5]
 [20.5 18.9]
 [20.1 22.2]
 [23.6 19.2]
 [16.8 19.9]
 [ 5.6  8.5]
 [50.  22.7]
 [14.5 11.7]
 [13.3 17.2]
 [23.9 25. ]
 [20.  19.7]
 [19.8 22.2]
 [13.8 11.7]
 [16.5 29.6]
 [21.6 18.9]
 [20.3 22.4]
 [17.  15.6]
 [11.8 13.4]
 [27.5 22.8]
 [15.6 14.8]
 [23.1 15.6]
 [24.3 19.3]
 [42.8 35.2]
 [15.6 15.6]
 [21.7 18.9]
 [17.1 20.9]
 [17.2 17.5]
 [15.  10.9]
 [21.7 22.5]
 [18.6 20.6]
 [21.  23.2]
 [33.1 29.6]
 [31.5 24. ]
 [20.1 21.8]
 [29.8 24.1]
 [15.2 17.4]
 [15.  27.1]
 [27.5 16.3]
 [22.6 21.7]
 [20.  24.4]
 [21.4 26.4]
 [23.5 24.8]
 [31.2 30.5]
 [23.7 25. ]
 [ 7.4  8.8]
 [48.3 41.7]

In [26]:
r2_score(y_test, y_pred)

0.5548780173995305

## Fitting RandomForest Rgression

In [27]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(
    n_estimators=50,
    random_state=0)
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=50,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [28]:
y_pred = rf.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[22.6   24.046]
 [50.    29.792]
 [23.    22.338]
 [ 8.3   11.132]
 [21.2   20.752]
 [19.9   20.534]
 [20.6   21.256]
 [18.7   20.102]
 [16.1   19.926]
 [18.6   18.898]
 [ 8.8    8.218]
 [17.2   14.24 ]
 [14.9   15.286]
 [10.5    8.638]
 [50.    46.226]
 [29.    33.524]
 [23.    20.846]
 [33.3   34.126]
 [29.4   25.844]
 [21.    21.162]
 [23.8   23.756]
 [19.1   21.966]
 [20.4   19.904]
 [29.1   24.67 ]
 [19.3   19.774]
 [23.1   18.63 ]
 [19.6   18.146]
 [19.4   16.198]
 [38.7   41.396]
 [18.7   19.372]
 [14.6   14.788]
 [20.    17.056]
 [20.5   20.02 ]
 [20.1   21.772]
 [23.6   22.718]
 [16.8   17.904]
 [ 5.6    8.848]
 [50.    29.312]
 [14.5   14.498]
 [13.3   15.552]
 [23.9   22.7  ]
 [20.    20.316]
 [19.8   22.622]
 [13.8   15.29 ]
 [16.5   23.398]
 [21.6   22.466]
 [20.3   21.662]
 [17.    16.6  ]
 [11.8   13.622]
 [27.5   25.018]
 [15.6   16.72 ]
 [23.1   19.654]
 [24.3   21.71 ]
 [42.8   39.39 ]
 [15.6   14.876]
 [21.7   21.122]
 [17.1   19.302]
 [17.2   18.976]
 [15.    23.79

In [29]:
r2_score(y_test, y_pred)

0.7739913545230002

### Grid search for n_estimator parameter

In [30]:
grid_search = GridSearchCV(
    estimator=rf,
    param_grid={'n_estimators':[50, 100, 200, 500, 800, 1000]},
    cv=10,
    n_jobs=-1
)
grid_search = grid_search.fit(X_train, y_train)
grid_search.best_params_

/home/its-k/anaconda3/envs/Learning/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'n_estimators': 1000}

In [31]:
best_rf = grid_search.best_estimator_

In [32]:
y_pred = best_rf.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[22.6   24.085]
 [50.    28.418]
 [23.    22.   ]
 [ 8.3   11.074]
 [21.2   20.806]
 [19.9   20.639]
 [20.6   21.218]
 [18.7   20.052]
 [16.1   20.444]
 [18.6   18.853]
 [ 8.8    8.331]
 [17.2   15.022]
 [14.9   15.068]
 [10.5    8.473]
 [50.    47.084]
 [29.    34.132]
 [23.    21.108]
 [33.3   34.687]
 [29.4   25.682]
 [21.    20.973]
 [23.8   23.726]
 [19.1   21.831]
 [20.4   19.839]
 [29.1   24.486]
 [19.3   20.305]
 [23.1   17.755]
 [19.6   18.535]
 [19.4   16.056]
 [38.7   44.109]
 [18.7   19.203]
 [14.6   14.879]
 [20.    17.518]
 [20.5   20.154]
 [20.1   21.51 ]
 [23.6   23.006]
 [16.8   17.913]
 [ 5.6    8.642]
 [50.    28.209]
 [14.5   14.563]
 [13.3   15.546]
 [23.9   22.808]
 [20.    20.914]
 [19.8   22.676]
 [13.8   15.226]
 [16.5   23.748]
 [21.6   22.485]
 [20.3   21.231]
 [17.    16.513]
 [11.8   14.482]
 [27.5   25.173]
 [15.6   16.27 ]
 [23.1   19.807]
 [24.3   21.967]
 [42.8   39.496]
 [15.6   15.002]
 [21.7   21.186]
 [17.1   19.671]
 [17.2   19.04 ]
 [15.    22.43

In [33]:
r2_score(y_test, y_pred)

0.7686590567675047

## Fitting Catboost Model

In [34]:
from catboost import CatBoostRegressor
cat_model = CatBoostRegressor()
cat_model.fit(X_train, y_train)

learn: 0.8195530	total: 5.43s	remaining: 3.4s
615:	learn: 0.8177180	total: 5.43s	remaining: 3.39s
616:	learn: 0.8157363	total: 5.44s	remaining: 3.38s
617:	learn: 0.8151008	total: 5.44s	remaining: 3.36s
618:	learn: 0.8141520	total: 5.45s	remaining: 3.35s
619:	learn: 0.8127314	total: 5.45s	remaining: 3.34s
620:	learn: 0.8119573	total: 5.46s	remaining: 3.33s
621:	learn: 0.8107609	total: 5.47s	remaining: 3.32s
622:	learn: 0.8094462	total: 5.47s	remaining: 3.31s
623:	learn: 0.8072759	total: 5.49s	remaining: 3.31s
624:	learn: 0.8057570	total: 5.49s	remaining: 3.29s
625:	learn: 0.8046138	total: 5.49s	remaining: 3.28s
626:	learn: 0.8032334	total: 5.5s	remaining: 3.27s
627:	learn: 0.8020424	total: 5.5s	remaining: 3.26s
628:	learn: 0.8005688	total: 5.51s	remaining: 3.25s
629:	learn: 0.7994367	total: 5.52s	remaining: 3.24s
630:	learn: 0.7985460	total: 5.52s	remaining: 3.23s
631:	learn: 0.7968578	total: 5.52s	remaining: 3.22s
632:	learn: 0.7966359	total: 5.53s	remaining: 3.21s
633:	learn: 0.794542

In [35]:
y_pred = cat_model.predict(X_test)
np.set_printoptions(precision=3)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[22.6   24.001]
 [50.    24.095]
 [23.    24.862]
 [ 8.3   10.608]
 [21.2   21.102]
 [19.9   20.132]
 [20.6   21.874]
 [18.7   19.972]
 [16.1   23.188]
 [18.6   19.678]
 [ 8.8    5.728]
 [17.2   13.878]
 [14.9   15.32 ]
 [10.5    9.837]
 [50.    48.41 ]
 [29.    33.425]
 [23.    21.563]
 [33.3   36.392]
 [29.4   28.166]
 [21.    21.969]
 [23.8   23.502]
 [19.1   21.564]
 [20.4   19.887]
 [29.1   26.502]
 [19.3   21.669]
 [23.1   19.634]
 [19.6   17.031]
 [19.4   16.558]
 [38.7   39.189]
 [18.7   19.279]
 [14.6   16.418]
 [20.    18.075]
 [20.5   20.323]
 [20.1   19.621]
 [23.6   24.816]
 [16.8   18.809]
 [ 5.6    8.516]
 [50.    23.041]
 [14.5   14.377]
 [13.3   16.418]
 [23.9   24.56 ]
 [20.    21.237]
 [19.8   21.34 ]
 [13.8   16.476]
 [16.5   23.125]
 [21.6   20.866]
 [20.3   20.292]
 [17.    18.006]
 [11.8   15.276]
 [27.5   23.754]
 [15.6   17.155]
 [23.1   22.002]
 [24.3   22.22 ]
 [42.8   37.83 ]
 [15.6   14.199]
 [21.7   21.526]
 [17.1   19.118]
 [17.2   18.463]
 [15.    17.68

In [36]:
r2_score(y_test, y_pred)

0.7006219582627364

## K-fold Cross Validation

In [38]:
from sklearn.model_selection import cross_val_score
models = [regressor, svr1, svr2, best_svr, dt, rf, best_rf, cat_model]
accuracies = []
for model in models:
    accuracy = cross_val_score(
        estimator=model,
        X=X_train,
        y=y_train,
        cv=10,
        n_jobs=-1)
    accuracies.append(accuracy)

In [45]:
a = {'Accuracy':[], 'Standard Deviation':[]}
for accuracy in accuracies:
    a['Accuracy'].append(accuracy.mean()*100)
    a['Standard Deviation'].append(accuracy.std()*100)

In [46]:
pd.DataFrame(a, index=['Linear Regressor', 'Linear SVR', 'SVR', 'Best SVR', 'Decision Tree', 'RandomForest', 'Best RandomForest', 'Catboost'])

Accuracy  Standard Deviation
Linear Regressor   73.101263           10.523659
Linear SVR         72.495541           11.292884
SVR                69.176262            8.411678
Best SVR           84.308086            6.175930
Decision Tree      74.587023           23.129935
RandomForest       85.823574            9.916977
Best RandomForest  86.436337            9.331951
Catboost           91.194747            4.021210